"""
Django settings for AinoteProject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from .log_config import LOGGING

# ログ設定
LOGGING = LOGGING

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5w5wxuqy!$tvj&1&e=97(3mu$=2hldjmv@@d93uc@ac$*9--%h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','ainote-django-app.onrender.com']
X_FRAME_OPTIONS = 'SAMEORIGIN'

SITE_DOMAIN = "http://127.0.0.1:8000"  # ローカル環境用
# 本番環境は以下のように変更
# SITE_DOMAIN = "https://your-production-domain.com"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # humanizeを有効化
    'django.conf.locale', # 日本語の翻訳ファイルを有効化

#    'maintenance_mode', #メンテナンスモード

    'AinoteProject',
    'top.apps.TopConfig',
    'mycalendar.apps.MycalendarConfig',
    'chat.apps.ChatConfig',
    'friend.apps.FriendConfig',
    'group.apps.GroupConfig',
    'user.apps.UserConfig',
    'room.apps.RoomConfig',
    'device.apps.DeviceConfig',
    'headline.apps.HeadlineConfig',
    'notice.apps.NoticeConfig',
    'place.apps.PlaceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

#    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'middleware.current_request.ThreadLocalMiddleware',
]

ROOT_URLCONF = 'AinoteProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AinoteProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Login Redirect
LOGIN_URL = "/top/login/"
#LOGIN_REDIRECT_URL = '/top/'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'
DATE_FORMAT = 'Y/m/d'             # 日付フォーマット (例: 2025/03/20)
DATETIME_FORMAT = 'Y/m/d H:i:s'   # 日時フォーマット

USE_I18N = True # 翻訳機能を有効にする
USE_L10N = True # 日付や数値のローカライズを有効にする
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# メンテナンス中でも管理サイトは使えるように。
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True

# is_superuserなユーザーはメンテナンス中でも通常ページが見れる。
MAINTENANCE_MODE_IGNORE_SUPERUSER = True
