# Generated by Django 5.1.6 on 2025-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Capacity')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('images', models.ImageField(blank=True, null=True, upload_to='room', verbose_name='Images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='room_pk')],
            },
        ),
    ]
