# Generated by Django 5.1.6 on 2025-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('images', models.ImageField(blank=True, null=True, upload_to='room', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='room', verbose_name='Themes')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacity')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('schedule_monthly', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Schedule Monthly')),
                ('schedule_weekly', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Schedule Weekly')),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
