# Generated by Django 5.1.6 on 2025-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_capacity_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='likes_record',
            field=models.TextField(blank=True, default='|', null=True),
        ),
    ]
