# Generated by Django 5.1.6 on 2025-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='google_schdule_monthly',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Google Schedule Monthly'),
        ),
        migrations.AddField(
            model_name='room',
            name='google_schdule_weekly',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Google Schedule Weekly'),
        ),
    ]
