# Generated by Django 5.1.6 on 2025-04-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_google_schdule_monthly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='google_schdule_monthly',
        ),
        migrations.RemoveField(
            model_name='room',
            name='google_schdule_weekly',
        ),
        migrations.AddField(
            model_name='room',
            name='schdule_month',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Schedule Monthly'),
        ),
        migrations.AddField(
            model_name='room',
            name='schdule_weekly',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Schedule Weekly'),
        ),
    ]
