# Generated by Django 5.1.6 on 2025-04-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_google_schdule_monthly_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='schdule_month',
            new_name='schdule_monthly',
        ),
    ]
