# Generated by Django 5.1.6 on 2025-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_context_group_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='group/', verbose_name='Images'),
        ),
    ]
