# Generated by Django 5.1.6 on 2025-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='context',
            field=models.TextField(verbose_name='Context'),
        ),
    ]
