# Generated by Django 5.1.6 on 2025-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Images'),
        ),
    ]
