# Generated by Django 5.1.6 on 2025-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_group_images'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='primary_key',
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('id',), name='group_pk'),
        ),
    ]
