# Generated by Django 5.1.6 on 2025-03-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_remove_group_primary_key_group_group_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
