# Generated by Django 5.1.6 on 2025-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_context_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
