# Generated by Django 5.1.6 on 2025-03-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_likes_group_likes_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='themes',
            field=models.ImageField(blank=True, null=True, upload_to='group', verbose_name='Themes'),
        ),
    ]
