# Generated by Django 5.1.6 on 2025-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_group_created_pic_group_updated_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='groups', to='group.groupcategory'),
        ),
    ]
