# Generated by Django 5.1.6 on 2025-04-12 08:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_groupcategory_group_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='categories',
        ),
        migrations.AddField(
            model_name='group',
            name='category_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('community', '地域活動'), ('sports', 'スポーツ'), ('walking', '歩活（ウォーキング）'), ('bbq', 'バーベキュー'), ('volunteer', 'ボランティア'), ('study', '勉強会・学習'), ('intergenerational', '世代交流'), ('childcare', '子育てサークル'), ('hobby', '趣味・創作'), ('music', '音楽・演奏'), ('other', 'その他')], max_length=200, null=True, verbose_name='Category Choice'),
        ),
        migrations.DeleteModel(
            name='GroupCategory',
        ),
    ]
