# Generated by Django 5.1.6 on 2025-04-13 05:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_remove_group_categories_group_category_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sports', '⚽スポーツ🏃\u200d♀️'), ('walking', '🚶\u200d♂️歩活（ウォーキング）🌳'), ('bbq', '🍖バーベキュー🔥'), ('music', '🎵音楽・演奏🎸'), ('study', '📚勉強会・学習🧠'), ('hobby', '🎨趣味・創作✂️'), ('childcare', '🍼子育てサークル👶'), ('volunteer', '🤝ボランティア👐'), ('intergenerational', '👨\u200d👩\u200d👧\u200d👦世代交流🕊️'), ('community', '🏘️地域活動👫'), ('other', '🧩その他🗂️')], max_length=200, null=True, verbose_name='Category Choice'),
        ),
    ]
