# Generated by Django 5.1.6 on 2025-04-18 16:06

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0028_remove_profile_contract_cource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('images', models.ImageField(blank=True, null=True, upload_to='sharedfile', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='sharedfile', verbose_name='Themes')),
                ('category_choice', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('student_roster', '🧑\u200d🎓生徒名簿管理表📋'), ('student_notes', '📖個別指導カルテ📝'), ('attendance', '⏰出席・欠席管理表🚪'), ('test_scores', '📊テスト結果記録・分析表🧪'), ('score_trends', '📈成績推移グラフツール📉'), ('understanding_check', '✅単元別理解度チェックシート🔍'), ('timetable', '🗓️時間割・講師シフト表👨\u200d🏫'), ('lesson_schedule', '📆授業スケジュール管理表📝'), ('contact_log', '📞保護者連絡記録表🗒️'), ('homework_check', '📚宿題提出チェック表✏️'), ('material_progress', '📘教材進捗管理表📏'), ('exam_plan', '🎯受験校リスト管理表🏫'), ('success_record', '🏆合格実績集計ツール📜'), ('interview_log', '💬面談記録シート🧾'), ('report_template', '🖨️保護者会資料作成テンプレート📑'), ('class_report', '📋クラス別成績レポート自動集計📐'), ('others', '🧰その他🗂️')], max_length=200, null=True, verbose_name='Category Choice')),
                ('files', models.FileField(blank=True, null=True, upload_to='sharedfile')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharedfile_created_pics', to='user.profile')),
                ('updated_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharedfile_updated_pics', to='user.profile')),
            ],
        ),
    ]
