# Generated by Django 5.1.6 on 2025-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='chat')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('order_by_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
