# Generated by Django 5.1.6 on 2025-03-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
    ]
