# Generated by Django 5.1.6 on 2025-03-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_images'),
        ('user', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='user.profile'),
        ),
    ]
