# Generated by Django 5.1.6 on 2025-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='likes',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='chat',
            name='likes_record',
            field=models.TextField(blank=True, default='|', null=True),
        ),
    ]
