# Generated by Django 5.1.6 on 2025-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_likes_chat_likes_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
