# Generated by Django 5.1.6 on 2025-03-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order_by_at',
            field=models.DateTimeField(null=True),
        ),
    ]
