# Generated by Django 5.1.6 on 2025-03-29 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_order_by_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='order_by_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 21, 8, 27, 241243), null=True),
        ),
    ]
