# Generated by Django 5.1.6 on 2025-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_order_by_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='order_by_at',
            field=models.DateTimeField(null=True),
        ),
    ]
