# Generated by Django 5.1.6 on 2025-04-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_order_by_at'),
        ('user', '0016_alter_profile_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pic', to='user.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pic', to='user.profile'),
        ),
    ]
