# Generated by Django 5.1.6 on 2025-04-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_created_pic_chat_updated_pic'),
        ('user', '0017_profile_created_pic_profile_updated_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_created_pics', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_updated_pics', to='user.profile'),
        ),
    ]
