# Generated by Django 5.1.6 on 2025-04-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_chat_created_pic_alter_chat_updated_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
