# Generated by Django 5.1.6 on 2025-04-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0013_delete_chat'),
        ('user', '0023_profile_threads_alter_profile_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='chat')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('order_by_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_created_pics', to='user.profile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='user.profile')),
                ('updated_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_updated_pics', to='user.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
