# Generated by Django 5.1.6 on 2025-04-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalChat',
        ),
    ]
