# Generated by Django 5.1.6 on 2025-04-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0022_profile_caretaker01_profile_caretaker02_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('images', models.ImageField(blank=True, null=True, upload_to='thread', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='thread', verbose_name='Themes')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_created_pics', to='user.profile')),
                ('updated_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_updated_pics', to='user.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='thread_pk')],
            },
        ),
    ]
