# Generated by Django 5.1.6 on 2025-04-19 16:22

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('images', models.ImageField(blank=True, null=True, upload_to='thread', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='thread', verbose_name='Themes')),
                ('category_choice', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('general_gaming', '🎮ゲーム好き集合！🧑\u200d💻'), ('battle_gaming', '⚔️バトル＆対戦好き集まれ🔥'), ('thrill_games', '👻ゾクゾクするゲーム体験🎢'), ('indie_games', '🕹️インディーズゲーム発掘隊🔍'), ('sports_fans', '🏀スポーツファン交流所🏃\u200d♂️'), ('oshi_talk', '🌟推し活・アイドルトーク💖'), ('entertainment_talk', '🎬エンタメ雑談広場🎉'), ('story_world', '📚創作・物語・世界観好き🌌'), ('philosophy_talk', '🧠知的＆哲学系トーク📖'), ('recommendations', '📢みんなのおすすめ紹介所📝'), ('free_talk', '💬なんでも雑談ルーム🕊️')], max_length=200, null=True, verbose_name='Category Choice')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='thread/chat')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('order_by_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
