# Generated by Django 5.1.6 on 2025-04-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thread', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_created_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_updated_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='threadchat',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_chat_created_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='threadchat',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile2thread_chats', to='user.profile'),
        ),
        migrations.AddField(
            model_name='threadchat',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread2chats', to='thread.thread'),
        ),
        migrations.AddField(
            model_name='threadchat',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_chat_updated_pics', to='user.profile'),
        ),
    ]
