# Generated by Django 5.1.6 on 2025-04-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_threadcategory_thread_categories'),
        ('user', '0023_profile_threads_alter_profile_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('order_by_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threadchat_created_pics', to='user.profile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threadchats', to='user.profile')),
                ('updated_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threadchat_updated_pics', to='user.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='threadchat_pk')],
            },
        ),
    ]
