# Generated by Django 5.1.6 on 2025-04-09 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_threadchat'),
        ('user', '0023_profile_threads_alter_profile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadchat',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
        migrations.AddField(
            model_name='threadchat',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='thread.thread'),
        ),
        migrations.AlterField(
            model_name='threadchat',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_created_pics', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='threadchat',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='threadchat',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_updated_pics', to='user.profile'),
        ),
    ]
