# Generated by Django 5.1.6 on 2025-04-09 03:37

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_alter_threadchat_images'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='threadchat',
            name='threadchat_pk',
        ),
        migrations.AlterField(
            model_name='threadchat',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='thread_chat'),
        ),
        migrations.AlterField(
            model_name='threadchat',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='thread.thread'),
        ),
    ]
