# Generated by Django 5.1.6 on 2025-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_remove_threadchat_threadchat_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadchat',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='thread_chat', verbose_name='Images'),
        ),
    ]
