# Generated by Django 5.1.6 on 2025-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0008_alter_threadchat_created_pic_alter_threadchat_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadchat',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='thread/chat'),
        ),
    ]
