# Generated by Django 5.1.6 on 2025-04-12 10:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0009_alter_threadchat_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='categories',
        ),
        migrations.AddField(
            model_name='thread',
            name='category_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('free_talk', 'なんでも雑談ルーム'), ('recommendations', 'みんなのおすすめ紹介所'), ('philosophy_talk', '知的＆哲学系トーク'), ('entertainment_talk', 'エンタメ雑談広場'), ('story_world', '創作・物語・世界観好き'), ('oshi_talk', '推し活・アイドルトーク'), ('general_gaming', 'ゲーム好き集合！'), ('indie_games', 'インディーズゲーム発掘隊'), ('battle_gaming', 'バトル＆対戦好き集まれ'), ('thrill_games', 'ゾクゾクするゲーム体験'), ('sports_fans', 'スポーツファン交流所')], max_length=200, null=True, verbose_name='Category Choice'),
        ),
        migrations.DeleteModel(
            name='ThreadCategory',
        ),
    ]
