# Generated by Django 5.1.6 on 2025-04-12 15:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0011_alter_thread_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('general_gaming', 'ゲーム好き集合！'), ('battle_gaming', 'バトル＆対戦好き集まれ'), ('thrill_games', 'ゾクゾクするゲーム体験'), ('indie_games', 'インディーズゲーム発掘隊'), ('sports_fans', 'スポーツファン交流所'), ('oshi_talk', '推し活・アイドルトーク'), ('entertainment_talk', 'エンタメ雑談広場'), ('story_world', '創作・物語・世界観好き'), ('philosophy_talk', '知的＆哲学系トーク'), ('recommendations', 'みんなのおすすめ紹介所'), ('free_talk', 'なんでも雑談ルーム')], max_length=200, null=True, verbose_name='Category Choice'),
        ),
    ]
