# Generated by Django 5.1.6 on 2025-04-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0026_remove_profile_profile_pk_alter_profile_memberid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Secret')], max_length=1, null=True, verbose_name='Gender')),
                ('images', models.ImageField(blank=True, null=True, upload_to='findme', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='findme', verbose_name='Themes')),
                ('birth_year', models.PositiveIntegerField(blank=True, choices=[(1895, '1895'), (1896, '1896'), (1897, '1897'), (1898, '1898'), (1899, '1899'), (1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], null=True, verbose_name='Birthday(Y)')),
                ('birth_month_day', models.DateField(blank=True, null=True, verbose_name='Birth(M/D))')),
                ('living_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Living Area')),
                ('mbti', models.CharField(blank=True, choices=[('-', '-'), ('INTJ', 'INTJ:想像力が豊かで、戦略的な思考の持ち主。あらゆる物事に対して計画を立てる。'), ('INTP', 'INTP:貪欲な知識欲を持つ革新的な発明家'), ('ENTJ', 'ENTJ:大胆で想像力豊か、かつ強い意志を持つ指導者。常に道を見つけるか、道を切り開く。'), ('ENTP', 'ENTP:賢くて好奇心旺盛な思考家。知的挑戦には必ず受けて立つ。'), ('INFJ', 'INFJ:物静かで神秘的だが、人々を非常に勇気づける飽くなき理想主義者'), ('ENFJ', 'ENFJ:カリスマ性があり、人々を励ますリーダー。聞く人を魅了する。'), ('INFP', 'INFP:詩人肌で親切な利他主義者。良い物事のためなら、いつでも懸命に手を差し伸べる。'), ('ENFP', 'ENFP:情熱的で独創力があり、かつ社交的な自由人。常に笑いほほ笑みの種を見つけられる。'), ('ISTJ', 'ISTJ:実用的で事実に基づいた思考の持ち主。その信頼性は紛れもなく本物。'), ('ISFJ', 'ISFJ:非常に献身的で心の温かい擁護者。いつでも大切な人を守る準備ができている。'), ('ESTJ', 'ESTJ:優秀な管理者で、物事や人々を管理する能力にかけては、右に出る者はいない。'), ('ESFJ', 'ESFJ:非常に思いやりがあり社交的で、人気がある。常に熱心に人々に手を差し伸べている。'), ('ESTP', 'ESTP:賢くてエネルギッシュで、非常に鋭い知覚の持ち主。危険と隣り合わせの人生を心から楽しむ。'), ('ISTP', 'ISTP:大胆で実践的な思考を持つ実験者。あらゆる道具を使いこなす。'), ('ISFP', 'ISFP:柔軟性と魅力がある芸術家。常に進んで物事を探索し経験しようとする。'), ('ESFP', 'ESFP:自発性がありエネルギッシュで熱心なエンターテイナー。周りが退屈することは決してない。')], max_length=4, null=True, verbose_name='MBTI Type')),
                ('mbti_name', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.CharField(blank=True, max_length=255, null=True, verbose_name='Overview')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='Introduce')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='Hobby')),
                ('foods', models.TextField(blank=True, null=True, verbose_name='Foods')),
                ('music', models.TextField(blank=True, null=True, verbose_name='Music')),
                ('movie', models.TextField(blank=True, null=True, verbose_name='Movie')),
                ('book', models.TextField(blank=True, null=True, verbose_name='Book')),
                ('favorite_type', models.TextField(blank=True, null=True, verbose_name='Favorite Type')),
                ('favorite_date', models.TextField(blank=True, null=True, verbose_name='Favorite Date')),
                ('sense_of_values', models.TextField(blank=True, null=True, verbose_name='Sense of Values')),
                ('future_plan', models.TextField(blank=True, null=True, verbose_name='Future Plan')),
                ('request_for_partner', models.TextField(blank=True, null=True, verbose_name='Request for partner')),
                ('weekend_activity', models.TextField(blank=True, null=True, verbose_name='Weekend Activity')),
                ('on_going_project', models.TextField(blank=True, null=True, verbose_name='On-Going Project')),
                ('on_going_event', models.TextField(blank=True, null=True, verbose_name='On-Going Event')),
                ('what_you_want_to_do', models.TextField(blank=True, null=True, verbose_name='What you want to do')),
                ('most_proud_event', models.TextField(blank=True, null=True, verbose_name='Most proud Event')),
                ('what_do_you_value_most', models.TextField(blank=True, null=True, verbose_name='What do you value most')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Contact')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findme_created_pics', to='user.profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('updated_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findme_updated_pics', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FindMeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='findme/images')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_theme', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('findme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findme_images', to='findme.findme')),
            ],
        ),
    ]
