# Generated by Django 5.1.6 on 2025-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findme',
            name='foods',
        ),
        migrations.AddField(
            model_name='findme',
            name='food',
            field=models.TextField(blank=True, null=True, verbose_name='Food'),
        ),
    ]
