# Generated by Django 5.1.6 on 2025-04-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findme', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findme',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findme_created_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='findme',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='findmes', to='user.profile'),
        ),
        migrations.AddField(
            model_name='findme',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findme_updated_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='findmeimage',
            name='findme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findme_images', to='findme.findme'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notifications', to='findme.findme'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_notifications', to='user.profile'),
        ),
        migrations.AddField(
            model_name='poke',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pokes', to='findme.findme'),
        ),
        migrations.AddField(
            model_name='poke',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pokes', to='user.profile'),
        ),
    ]
