# Generated by Django 5.1.6 on 2025-04-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0002_remove_findme_foods_findme_food'),
        ('user', '0026_remove_profile_profile_pk_alter_profile_memberid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findme',
            name='what_do_you_value_most',
        ),
        migrations.AddField(
            model_name='findme',
            name='what_you_value_most',
            field=models.TextField(blank=True, null=True, verbose_name='What you value most'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='findmes', to='user.profile'),
        ),
    ]
