# Generated by Django 5.1.6 on 2025-04-11 12:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0005_alter_findme_living_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='findme',
            name='food_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('japanese', '和食'), ('western', '洋食'), ('chinese', '中華料理'), ('korean', '韓国料理'), ('italian', 'イタリアン'), ('french', 'フレンチ'), ('thai', 'タイ料理'), ('indian', 'インド料理'), ('sweets', 'スイーツ'), ('fastfood', 'ファストフード'), ('healthy', '健康志向料理'), ('home', '家庭料理'), ('other', 'その他')], max_length=200, null=True, verbose_name='Food Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='hobby_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('music', '音楽鑑賞'), ('movie', '映画鑑賞'), ('travel', '旅行'), ('sports', 'スポーツ'), ('reading', '読書'), ('cooking', '料理')], max_length=200, null=True, verbose_name='Hobby Choice'),
        ),
    ]
