# Generated by Django 5.1.6 on 2025-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0006_findme_food_choice_alter_findme_hobby_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findme',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', '秘密'), ('M', '男性'), ('F', '女性')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
