# Generated by Django 5.1.6 on 2025-04-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0008_rename_favorite_type_findme_personality_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findme',
            old_name='on_going_project',
            new_name='ongoing_project',
        ),
        migrations.RenameField(
            model_name='findme',
            old_name='on_going_project_choice',
            new_name='ongoing_project_choice',
        ),
    ]
