# Generated by Django 5.1.6 on 2025-04-13 01:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0009_rename_on_going_project_findme_ongoing_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findme',
            name='book_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('novel', '📖小説📝'), ('mystery', '🕵️ミステリー🔍'), ('romance', '💘恋愛/ラブストーリー💌'), ('fantasy', '🧝ファンタジー🦄'), ('sci-fi', '👽SF/サイエンスフィクション🚀'), ('historical', '🏯歴史小説📜'), ('thriller', '🔪スリラー/サスペンス😱'), ('essay', '📝エッセイ📄'), ('poetry', '🖋️詩/短歌/俳句🌸'), ('nonfiction', '📚ノンフィクション📘'), ('biography', '👤伝記🖊️'), ('business', '💼ビジネス書📈'), ('selfhelp', '🌟自己啓発💪'), ('psychology', '🧠心理学🛋️'), ('philosophy', '🤔哲学/思想📚'), ('science', '🔬科学/理系⚛️'), ('religion', '🕊️宗教/精神世界🛐'), ('education', '🎓教育/子育て👶'), ('comic', '📙漫画😂'), ('lightnovel', '📘ライトノベル✨'), ('literature', '📝純文学🏛️'), ('classic', '🏺古典文学📖'), ('other', '❓その他📗')], max_length=200, null=True, verbose_name='Book Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='favorite_date_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cafe', '☕カフェでゆっくり話す🧁'), ('dinner', '🍷おしゃれなレストランでディナー🍽️'), ('movie', '🎬映画鑑賞デート🍿'), ('park', '🌳公園で散歩🚶\u200d♀️'), ('amusement_park', '🎡遊園地・テーマパーク🎢'), ('aquarium', '🐠水族館デート🐧'), ('zoo', '🦁動物園デート🐵'), ('museum', '🖼️美術館・博物館巡り🏛️'), ('shopping', '🛍️一緒にショッピング💳'), ('drive', '🚗ドライブデート🌆'), ('beach', '🏖️海辺でのんびり🌅'), ('picnic', '🧺自然の中でピクニック🌼'), ('hiking', '🥾ハイキング・登山⛰️'), ('festival', '🎆夏祭り・花火大会👘'), ('hot_spring', '♨️温泉旅行🏞️'), ('home_cooking', '🍳おうちで一緒に料理🥗'), ('game_night', '🎮おうちでゲーム・映画鑑賞📺'), ('sports', '🏀一緒にスポーツをする🏃\u200d♂️'), ('concert', '🎤ライブ・コンサート鑑賞🎶'), ('season_event', '🌸季節イベント（花見・紅葉など）🍁'), ('travel', '🧳日帰りor泊まり旅行✈️'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='Favorite Date Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='food_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('japanese', '🍱和食🍚'), ('western', '🍔洋食🥩'), ('chinese', '🥡中華料理🥢'), ('korean', '🌶️韓国料理🥘'), ('italian', '🍝イタリアン🍕'), ('french', '🥖フレンチ🍷'), ('thai', '🍜タイ料理🌶️'), ('indian', '🍛インド料理🧄'), ('sweets', '🍰スイーツ🍩'), ('fastfood', '🍟ファストフード🍔'), ('healthy', '🥗健康志向料理🍵'), ('home', '🏠家庭料理🍳'), ('other', '❓その他🍽️')], max_length=200, null=True, verbose_name='Food Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='free_day_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nature_escape', '🏞️自然の中で過ごす（ハイキング、キャンプ、ビーチでリラックスなど）🌳'), ('city_exploration', '🏙️街を散策する（カフェ巡り、観光名所巡りなど）🏙️'), ('creative_hobby', '🎨クリエイティブな趣味を楽しむ（絵を描く、音楽を作る、料理するなど）🎶'), ('adventure', '🧗\u200d♂️冒険的な体験をする（スポーツ、バンジージャンプ、旅行など）🌍'), ('spa_and_relax', '💆\u200d♀️スパやリラックスする時間を過ごす（温泉、マッサージ、瞑想など）🛁'), ('family_time', '👨\u200d👩\u200d👧\u200d👦家族と過ごす（みんなで料理、ゲーム、外食など）🍽️'), ('friends_gathering', '🍻友達と過ごす（ピクニック、飲み会、カラオケなど）🎤'), ('reading_and_study', '📚読書や学びの時間を持つ（本を読む、新しいスキルを学ぶなど）🖋️'), ('indoor_relax', '🎮家でのんびり過ごす（映画鑑賞、ゲーム、ネットサーフィンなど）🛋️'), ('volunteering', '🤝社会貢献活動に参加する（ボランティア活動、地域イベント支援など）🌍'), ('sports_and_fitness', '🏋️\u200d♂️スポーツやフィットネスに挑戦する（ジム、ヨガ、ジョギングなど）🏃\u200d♀️'), ('culinary_experience', '🍣美味しい食事を楽しむ（グルメ巡り、料理教室など）🍷'), ('travel_abroad', '✈️海外旅行に行く（異文化交流、観光など）🌏'), ('luxury_experience', '💎贅沢な体験をする（高級レストラン、リゾート地など）🍽️'), ('watching_performance', '🎭演劇やライブを観る（コンサート、映画、演劇など）🎶'), ('silent_retreat', '🧘\u200d♀️静かな場所で過ごす（リトリート、瞑想、静寂な場所でのひとときなど）🌿'), ('other', '❓その他の過ごし方💬')], max_length=200, null=True, verbose_name='Free Day Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='future_plan_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('entrepreneur', '💼起業したい🚀'), ('career_up', '📈キャリアアップしたい🌟'), ('expert', '👨\u200d🔬専門分野で一流になりたい🎓'), ('side_job', '💻副業をしたい💡'), ('overseas', '🌍海外で働きたい・暮らしたい✈️'), ('creative', '🎨創作活動をしたい（音楽・アートなど）🎶'), ('freelance', '🖥️フリーランスで働きたい👩\u200d💻'), ('volunteer', '🤝社会貢献・ボランティア活動をしたい🌱'), ('family', '👨\u200d👩\u200d👧\u200d👦家庭を築きたい・子育てしたい🏡'), ('community', '🏘️地域活動に関わりたい🤝'), ('relaxed_life', '🌿のんびりとした生活を送りたい🌅'), ('financial_freedom', '💸経済的自由を得たい（脱サラなど）🏝️'), ('study', '📚もう一度勉強したい・学び直したい🎓'), ('adventure', '🌎世界を旅したい・冒険したい🏞️'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='Future Plan Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', '🌈秘密🤫'), ('M', '👦男性👔'), ('F', '👧女性👠')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='hobby_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('music', '🎧音楽鑑賞🎶'), ('movie', '🎬映画鑑賞🍿'), ('travel', '✈️旅行🌍'), ('sports', '⚽スポーツ🏃'), ('reading', '📚読書📖'), ('cooking', '🍳料理🧂')], max_length=200, null=True, verbose_name='Hobby Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='living_pref',
            field=models.CharField(blank=True, choices=[('-', '-'), ('hokkaido', '❄️北海道🐄'), ('aomori', '🍎青森県🌊'), ('iwate', '⛰️岩手県🏞️'), ('miyagi', '🐟宮城県🏯'), ('akita', '🐶秋田県🌾'), ('yamagata', '🍒山形県🌸'), ('fukushima', '🏔️福島県🧴'), ('ibaraki', '🥬茨城県🏖️'), ('tochigi', '🍓栃木県🚗'), ('gunma', '♨️群馬県🐴'), ('saitama', '🌻埼玉県🚉'), ('chiba', '🐬千葉県🛫'), ('tokyo', '🗼東京都🎌'), ('kanagawa', '⚓神奈川県🏖️'), ('niigata', '🌾新潟県🎿'), ('toyama', '🏔️富山県🐟'), ('ishikawa', '🏯石川県🎨'), ('fukui', '🦖福井県🏞️'), ('yamanashi', '🍇山梨県🗻'), ('nagano', '❄️長野県🥢'), ('gifu', '🏯岐阜県🍡'), ('shizuoka', '🗻静岡県🐟'), ('aichi', '🚄愛知県🏯'), ('mie', '⛩️三重県🐚'), ('shiga', '🌊滋賀県🦢'), ('kyoto', '🎋京都府🏯'), ('osaka', '🍜大阪府🎭'), ('hyogo', '🦌兵庫県⛴️'), ('nara', '🦌奈良県🏺'), ('wakayama', '🍊和歌山県🐼'), ('tottori', '🐪鳥取県⛱️'), ('shimane', '🦀島根県🏮'), ('okayama', '🍑岡山県🏞️'), ('hiroshima', '🕊️広島県⛩️'), ('yamaguchi', '🐡山口県🏯'), ('tokushima', '🎵徳島県🌀'), ('kagawa', '🍜香川県🧂'), ('ehime', '🍊愛媛県⛴️'), ('kouchi', '🏞️高知県🐎'), ('fukuoka', '🍜福岡県🎉'), ('saga', '🛤️佐賀県🍵'), ('nagasaki', '⚓長崎県⛪'), ('kumamoto', '🐻熊本県🏯'), ('oita', '♨️大分県🐵'), ('miyazaki', '🌴宮崎県🐓'), ('kagoshima', '🌋鹿児島県🛳️'), ('okinawa', '🏖️沖縄県🥁')], max_length=10, null=True, verbose_name='Living Pref.'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='most_important_values_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('family', '👨\u200d👩\u200d👧\u200d👦家族（家族との絆、親子関係など）🧑\u200d👧\u200d👦'), ('friendship', '🤝友情（友人との関係、信頼や支え合い）👬'), ('health', '💪健康（身体的・精神的な健康を維持すること）🏋️\u200d♀️'), ('honesty', '🕊️正直（誠実であること、嘘をつかないこと）⚖️'), ('career', '💼キャリア（仕事の成長や目標達成）📈'), ('financial_stability', '💰経済的安定（お金の管理や将来のための準備）🏦'), ('self_development', '📚自己成長（新しいスキルを学ぶこと、人生の経験から学ぶこと）🧠'), ('compassion', '💖思いやり（他者への優しさや助け合いの精神）🤗'), ('integrity', '🔒誠実さ（道徳的・倫理的に正しいことをする）🛡️'), ('adventure', '🌍冒険心（新しいことに挑戦すること、未知の経験をすること）🧭'), ('creativity', '🎨創造性（芸術や新しいアイデアを生み出すこと）💡'), ('peace_of_mind', '☮️心の平穏（ストレスの少ない生活、精神的な安定）🧘\u200d♂️'), ('freedom', '🕊️自由（自分らしく生きること、制約からの解放）🚀'), ('justice', '⚖️正義（公平で公正な社会を目指すこと）🕊️'), ('love', '❤️愛（愛情を持ち続けること、関係性の深さ）💑'), ('environment', '🌿環境（自然保護や持続可能な生活）🌍'), ('other', '❓その他の大切にしていること❕')], max_length=200, null=True, verbose_name='Most important Values Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='movie_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('action', '💥アクション🎯'), ('adventure', '🗺️アドベンチャー🧭'), ('comedy', '😂コメディ🎭'), ('drama', '🎬ドラマ🎟️'), ('romance', '❤️恋愛/ラブロマンス💌'), ('thriller', '😱スリラー/サスペンス🔪'), ('horror', '👻ホラー🧟'), ('mystery', '🕵️ミステリー🔍'), ('sci-fi', '🚀SF/サイエンスフィクション👽'), ('fantasy', '🧙ファンタジー🦄'), ('animation', '🎨アニメーション📽️'), ('documentary', '📚ドキュメンタリー🎞️'), ('musical', '🎤ミュージカル🎶'), ('history', '🏛️歴史📜'), ('biography', '👤伝記🖋️'), ('war', '⚔️戦争🪖'), ('crime', '🚓犯罪/クライム🕶️'), ('family', '👨\u200d👩\u200d👧\u200d👦ファミリー🧸'), ('superhero', '🦸ヒーロー/特撮⚡'), ('japanese', '🎌邦画🎥'), ('foreign', '🌍洋画🌐'), ('other', '❓その他🎬')], max_length=200, null=True, verbose_name='Movie Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='music_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pop', '🎤ポップス🎶'), ('rock', '🎸ロック🤘'), ('jazz', '🎷ジャズ🕶️'), ('classical', '🎻クラシック🎼'), ('hiphop', '🧢ヒップホップ/ラップ🎧'), ('edm', '🎚️EDM/ダンス💃'), ('rnb', '🎙️R&B/ソウル❤️'), ('anime', '🌟アニメソング🎵'), ('game', '🎮ゲーム音楽🕹️'), ('kpop', '🇰🇷K-POP💫'), ('enka', '🌸演歌🎤'), ('idol', '💖アイドル🌟'), ('folk', '🪕フォーク/カントリー🎶'), ('metal', '🤘メタル/ハードロック🔥'), ('reggae', '🟰レゲエ🧘'), ('blues', '🎺ブルース💙'), ('world', '🌍ワールドミュージック🎶'), ('other', '❓その他🎼')], max_length=200, null=True, verbose_name='Music Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='ongoing_project_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('career_development', '💼キャリアの成長・スキルアップ📈'), ('startup', '🚀起業・スタートアップ💡'), ('freelance', '💻フリーランスの仕事🏠'), ('research', '🔬研究・調査📊'), ('side_project', '💼副業プロジェクト📅'), ('hobby_project', '🎨趣味でのプロジェクト（アート、音楽、写真など）📸'), ('learning', '📚新しい技術や言語の学習🖥️'), ('fitness', '🏋️\u200d♀️健康・フィットネス（ジム、ダイエット、ヨガなど）🧘\u200d♂️'), ('volunteering', '🤝ボランティア活動🌍'), ('community_building', '🏘️コミュニティ作り・参加👥'), ('travel', '✈️旅行計画・実行🌍'), ('personal_growth', '🌱自己成長・心理学の学習🧠'), ('writing', '✍️執筆（ブログ、小説、詩など）📖'), ('creative_work', '🎨創作活動（絵画、音楽、映像制作など）🎬'), ('event_organizing', '🎉イベントの企画・運営📅'), ('productivity', '⏰生産性向上の取り組み（習慣化、時間管理など）📈'), ('innovation', '💡イノベーション・新しいアイディアの実現🚀'), ('social_project', '🌍社会貢献活動（環境保護、社会問題解決など）♻️'), ('family', '👨\u200d👩\u200d👧\u200d👦家庭や育児に関連する活動🏡'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='On-Going Project Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='personality_type_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('easygoing', '🌿おおらか☀️'), ('serious', '📘真面目🧐'), ('sociable', '🤝社交的😄'), ('calm', '🧘\u200d♂️落ち着いている🌊'), ('my_pace', '🐢マイペース🚶\u200d♂️'), ('positive', '🌈ポジティブ💪'), ('sensitive', '🌸繊細💧'), ('energetic', '⚡元気・活発🏃\u200d♂️'), ('quiet', '🤫おとなしい🌙'), ('curious', '🔍好奇心旺盛🧠'), ('logical', '🧩論理的🧠'), ('emotional', '💖感情豊か😭'), ('cheerful', '😄明るい🌞'), ('friendly', '😊フレンドリー🤗'), ('ambitious', '🚀向上心がある🎯'), ('considerate', '🤝思いやりがある💐'), ('independent', '🦅自立している🧍\u200d♂️'), ('careful', '🔒慎重派🕵️\u200d♂️'), ('adaptable', '🌊柔軟に対応できる🔄'), ('leader', '👑リーダーシップがある🗣️'), ('listener', '👂聞き上手🤲'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='Favorite Type Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='proudest_achievements_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('academic_success', '🎓学業や資格取得（大学の卒業、資格試験の合格など）📚'), ('career_achievement', '💼キャリアの達成（昇進、プロジェクトの成功、起業など）🚀'), ('personal_growth', '🌱自己成長（新しいスキルの習得、マインドセットの変化など）💡'), ('family_relationship', '👨\u200d👩\u200d👧\u200d👦家族との関係（親との絆を深めた、子供の育成など）❤️'), ('volunteering_contribution', '🤝社会貢献（ボランティア活動、コミュニティへの貢献など）🌍'), ('overcoming_adversity', '💪困難の克服（健康問題、経済的困難などを乗り越えた経験）🛠️'), ('artistic_creativity', '🎨芸術的な成果（絵を描いた、音楽を作った、演技をしたなど）🎶'), ('sports_achievement', '🏅スポーツの成果（大会での優勝、自己記録の更新など）🏆'), ('travel_experience', '✈️旅行で得た経験（海外一人旅、異文化交流など）🌏'), ('relationships', '🤗人間関係の構築（友人との絆、恋愛関係などの成功）💑'), ('financial_success', '💰経済的成功（貯金、投資での成功、マイホーム購入など）🏠'), ('personal_project', '💼個人的なプロジェクト（自分で始めた事業や活動など）🛠️'), ('helping_others', '🤗他人を助けた経験（他人の成功に貢献した、自分が助けた話など）🙌'), ('milestone_event', '🎉人生の節目となる出来事（結婚、子供の誕生、大きな旅行など）💍'), ('other', '❓その他の誇りに思うこと💬')], max_length=200, null=True, verbose_name='Proudest Achievement Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='request_for_partner_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kind', '💖思いやりがある🤗'), ('honest', '🧐誠実で正直🙌'), ('funny', '😂ユーモアがある🤣'), ('reliable', '💪頼りがいがある🛠️'), ('calm', '😌落ち着いている🌿'), ('positive', '🌟ポジティブ思考✨'), ('respectful', '🙏相手を尊重する🤝'), ('empathetic', '💞共感力がある🤗'), ('good_communicator', '🗣️コミュニケーション能力が高い📞'), ('romantic', '💘ロマンチック💐'), ('intellectual', '🧠知的で教養がある📚'), ('active', '🏃\u200d♂️行動的・アウトドア派🏞️'), ('creative', '🎨創造力がある💡'), ('similar_values', '💬価値観が似ている🤍'), ('family_oriented', '👨\u200d👩\u200d👧\u200d👦家庭を大事にする🏡'), ('financially_stable', '💸経済的に安定している🏦'), ('appearance', '😍外見が好み💅'), ('independent', '💼自立している💪'), ('listener', '👂話をしっかり聞いてくれる👂'), ('affectionate', '💋愛情表現が豊か💖'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='Request for partner Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='sense_of_values_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('trust', '🤝信頼関係🔒'), ('honesty', '🕊️正直さ🪞'), ('communication', '🗣️しっかり話し合えること💬'), ('respect', '🙇\u200d♀️お互いを尊重すること🙇\u200d♂️'), ('humor', '😂ユーモア・笑いのセンス🤪'), ('affection', '💞愛情表現💋'), ('shared_values', '🧠価値観の一致❤️'), ('support', '🤗困った時に支え合えること🆘'), ('freedom', '🕊️お互いの自由を尊重すること🛫'), ('growth', '🌱一緒に成長できること📈'), ('passion', '🔥情熱・ドキドキ感❤️\u200d🔥'), ('reliability', '🛡️頼りがい🧍\u200d♂️'), ('stability', '⚖️安定感🧱'), ('romance', '🌹ロマンチックな関係🌙'), ('fun', '🎉一緒にいて楽しいこと🥳'), ('goals', '🎯将来の目標や夢の共有🚀'), ('family_mind', '🏡家庭的であること👨\u200d👩\u200d👧\u200d👦'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='Sense of Values Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='social_activity_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('environmental_protection', '🌱環境保護活動（リサイクル、植樹、環境教育など）🌍'), ('animal_welfare', '🐾動物福祉活動（動物保護団体、保護施設支援など）🐶'), ('disaster_relief', '🚨災害支援活動（被災地支援、募金活動など）💖'), ('education_support', '📚教育支援活動（子どもの学習支援、教育普及活動など）👩\u200d🏫'), ('healthcare', '🩺医療支援活動（病院支援、医療ボランティアなど）💉'), ('poverty_alleviation', '🍞貧困救済活動（食料支援、物資配布など）🏘️'), ('elderly_support', '👵高齢者支援活動（訪問介護、シニア向けプログラムなど）👴'), ('community_development', '🏡地域社会開発（地域イベントの企画、地域活性化など）🌆'), ('refugee_support', '🌍難民支援活動（難民キャンプの支援、物資提供など）🆘'), ('human_rights', '✊人権活動（平等、自由の促進、LGBTQ+支援など）🏳️\u200d🌈'), ('gender_equality', '♀️ジェンダー平等活動（女性の権利向上、性別に関する教育など）♂️'), ('youth_mentorship', '👩\u200d🏫若者支援（メンターとして活動、若者向けプログラムなど）👨\u200d🏫'), ('community_health', '💪地域の健康推進活動（予防接種、健康診断など）🏥'), ('arts_and_culture', '🎨アート・文化活動（地域の文化祭支援、アートプロジェクトなど）🎭'), ('sports_and_recreation', '⚽スポーツ・レクリエーション支援（地域スポーツイベントの開催など）🏅'), ('clean_up', '🧹地域清掃活動（ビーチクリーンアップ、街のゴミ拾いなど）🗑️'), ('social_inclusion', '🤝社会的包摂活動（マイノリティ支援、孤立を防ぐ活動など）🌍'), ('mental_health', '🧠メンタルヘルス支援（カウンセリング、精神的支援活動など）💙'), ('tech_for_good', '💻テクノロジーを活用した社会貢献（IT教育、オンライン支援プラットフォームなど）🌐'), ('other', '❓その他の社会活動💬')], max_length=200, null=True, verbose_name='Social Activity Choice'),
        ),
        migrations.AlterField(
            model_name='findme',
            name='weekend_activity_choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('outdoor', '🏞️アウトドア（登山・散歩・サイクリングなど）🚶\u200d♀️'), ('movie', '🎬映画鑑賞🍿'), ('cafe', '☕カフェ巡り🍰'), ('reading', '📚読書📖'), ('shopping', '🛍️買い物👗'), ('cooking', '🍳料理👨\u200d🍳'), ('gaming', '🎮ゲーム🎲'), ('art', '🎨アート・美術館巡り🖼️'), ('study', '📘勉強・資格取得のための学習📝'), ('music', '🎶音楽を聴く・演奏する🎸'), ('exercise', '💪ジム・ヨガなどの運動🧘\u200d♀️'), ('travel', '✈️ひとり旅・日帰り旅行🗺️'), ('relax', '🛋️自宅でのんびり・ゴロゴロする💤'), ('photo', '📸写真撮影・インスタ巡り🖼️'), ('social', '💻SNS・ネットサーフィン🌐'), ('hobby', '🎨趣味に没頭する🧩'), ('volunteer', '🤝ボランティア活動🌍'), ('spiritual', '⛩️神社仏閣巡り・パワースポット巡り🕉️'), ('other', '❓その他💭')], max_length=200, null=True, verbose_name='Weekend Activity Choice'),
        ),
    ]
