# Generated by Django 5.1.6 on 2025-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0013_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='findmeimage',
            name='image_category_choice',
            field=models.CharField(blank=True, choices=[('smile', '😊笑顔😄'), ('fashion', '👗オシャレ🕶️'), ('hobby_action', '🎨趣味🎸'), ('pet_love', '🐶ペット🐱'), ('outdoor', '🌄自然・お出かけ🚴'), ('sports_pose', '🏋️\u200d♂️スポーツ・健康美💪'), ('foodie', '🍳手料理・グルメ🍰'), ('culture', '📚知的・文化的🧠'), ('mystery', '🎭ミステリアス🌙'), ('funny', '😂ユーモア🤪')], max_length=100, null=True, verbose_name='Image Category'),
        ),
    ]
