# Generated by Django 5.1.6 on 2025-04-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0014_findmeimage_image_category_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poke',
            unique_together=set(),
        ),
    ]
