# Generated by Django 5.1.6 on 2025-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='maker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maker'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='productno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ProductNo'),
        ),
    ]
