# Generated by Django 5.1.6 on 2025-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_maker_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='likes_record',
            field=models.TextField(blank=True, default='|', null=True),
        ),
    ]
