# Generated by Django 5.1.6 on 2025-04-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='schedule_monthly',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Schedule Monthly'),
        ),
        migrations.AddField(
            model_name='device',
            name='schedule_weekly',
            field=models.CharField(blank=True, max_length=1028, null=True, verbose_name='Schedule Weekly'),
        ),
    ]
