# Generated by Django 5.1.6 on 2025-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('images', models.ImageField(blank=True, null=True, upload_to='place', verbose_name='Images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='place_pk')],
            },
        ),
    ]
