# Generated by Django 5.1.6 on 2025-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='Checkin')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='Checkout')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('images', models.ImageField(blank=True, null=True, upload_to='place', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='place', verbose_name='Themes')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('likes_record', models.TextField(blank=True, default='|', null=True)),
                ('schedule_monthly', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Schedule Monthly')),
                ('schedule_weekly', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Schedule Weekly')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('googlemap_url', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Google Map URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
