# Generated by Django 5.1.6 on 2025-04-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='place',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_created_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_updated_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.place', verbose_name='Place'),
        ),
    ]
