# Generated by Django 5.1.6 on 2025-03-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='themes',
            field=models.ImageField(blank=True, null=True, upload_to='place', verbose_name='Themes'),
        ),
        migrations.AlterField(
            model_name='place',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel'),
        ),
    ]
