# Generated by Django 5.1.6 on 2025-03-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_themes_alter_place_company_alter_place_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='likes_record',
            field=models.TextField(blank=True, default='|', null=True),
        ),
    ]
