# Generated by Django 5.1.6 on 2025-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_likes_place_likes_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
    ]
