# Generated by Django 5.1.6 on 2025-03-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_place_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='company',
        ),
        migrations.AddField(
            model_name='place',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area'),
        ),
    ]
