# Generated by Django 5.1.6 on 2025-03-29 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_remove_place_company_place_area'),
        ('user', '0011_profile_given_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='Checkin')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='Checkout')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.place', verbose_name='Place')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.profile', verbose_name='Profile')),
            ],
        ),
    ]
