# Generated by Django 5.1.6 on 2025-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='googlemap_url',
            field=models.TextField(blank=True, null=True, verbose_name='Google Map URL'),
        ),
    ]
