# Generated by Django 5.1.6 on 2025-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_place_googlemap_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='googlemap_url',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Google Map URL'),
        ),
    ]
