# Generated by Django 5.1.6 on 2025-03-20 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='user.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='user.profile')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('profile1_id__lt', models.F('profile2_id'))), name='check_profile_order')],
                'unique_together': {('profile1', 'profile2')},
            },
        ),
    ]
