# Generated by Django 5.1.6 on 2025-04-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
        ('user', '0017_profile_created_pic_profile_updated_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_created_pics', to='user.profile'),
        ),
    ]
