# Generated by Django 5.1.6 on 2025-04-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friend', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_created_pics', to='user.profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='user.profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='user.profile'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.CheckConstraint(condition=models.Q(('profile1_id__lt', models.F('profile2_id'))), name='check_profile_order'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('profile1', 'profile2')},
        ),
    ]
