# Generated by Django 5.1.6 on 2025-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='notice', verbose_name='Images')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Period')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Published at')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
