# Generated by Django 5.1.6 on 2025-03-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('context', models.TextField(verbose_name='Context')),
                ('images', models.ImageField(blank=True, null=True, upload_to='group', verbose_name='Images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='notice_pk')],
            },
        ),
    ]
