# Generated by Django 5.1.6 on 2025-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.AddField(
            model_name='notice',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='notice', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
