# Generated by Django 5.1.6 on 2025-03-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_overview_notice_period_alter_notice_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AddField(
            model_name='notice',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
