# Generated by Django 5.1.6 on 2025-03-20 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='ログイン時刻')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='ログアウト時刻')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Member Id')),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nick Name')),
                ('birthday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Birthday')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('badges', models.CharField(blank=True, choices=[('light', 'White'), ('primary', 'Blue'), ('danger', 'Red'), ('success', 'Green'), ('warning', 'Yellow'), ('info', 'Sky'), ('secondary', 'Gray'), ('dark', 'Black')], max_length=30, null=True, verbose_name='Badges')),
                ('images', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Images')),
                ('themes', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Themes')),
                ('staff_flg', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('memberid',), name='profile_pk')],
            },
        ),
    ]
