# Generated by Django 5.1.6 on 2025-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_group_remarks'),
        ('user', '0005_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='group.group'),
        ),
    ]
