# Generated by Django 5.1.6 on 2025-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book',
            field=models.TextField(blank=True, null=True, verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='event',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='Hobby'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movie',
            field=models.TextField(blank=True, null=True, verbose_name='Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='music',
            field=models.TextField(blank=True, null=True, verbose_name='Music'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sports',
            field=models.TextField(blank=True, null=True, verbose_name='Sports'),
        ),
    ]
