# Generated by Django 5.1.6 on 2025-03-23 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_book_profile_event_profile_hobby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceRecord',
            new_name='LoginRecord',
        ),
    ]
