# Generated by Django 5.1.6 on 2025-03-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_attendancerecord_loginrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff_flg',
        ),
    ]
