# Generated by Django 5.1.6 on 2025-03-23 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_profile_staff_flg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logout'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
