# Generated by Django 5.1.6 on 2025-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_loginrecord_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='given_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
