# Generated by Django 5.1.6 on 2025-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, choices=[('INTJ', '建築家'), ('INTP', '論理学者'), ('ENTJ', '指揮官'), ('ENTP', '討論者'), ('INFJ', '提唱者'), ('ENFJ', '主人公'), ('INFP', '仲介者'), ('ENFP', '運動家'), ('ISTJ', '管理者'), ('ISFJ', '擁護者'), ('ESTJ', '幹部'), ('ESFJ', '領事'), ('ESTP', '起業家'), ('ISTP', '巨匠'), ('ISFP', '冒険家'), ('ESFP', 'エンターテイナー')], max_length=4, null=True, verbose_name='MBTI Type'),
        ),
    ]
