# Generated by Django 5.1.6 on 2025-04-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, choices=[('-', '-'), ('INTJ', 'INTJ:建築家'), ('INTP', 'INTP:論理学者'), ('ENTJ', 'ENTJ:指揮官'), ('ENTP', 'ENTP:討論者'), ('INFJ', 'INFJ:提唱者'), ('ENFJ', 'ENFJ:主人公'), ('INFP', 'INFP:仲介者'), ('ENFP', 'ENFP:運動家'), ('ISTJ', 'ISTJ:管理者'), ('ISFJ', 'ISFJ:擁護者'), ('ESTJ', 'ESTJ:幹部'), ('ESFJ', 'ESFJ:領事'), ('ESTP', 'ESTP:起業家'), ('ISTP', 'ISTP:巨匠'), ('ISFP', 'ISFP:冒険家'), ('ESFP', 'ESFP:エンターテイナー')], max_length=4, null=True, verbose_name='MBTI Type'),
        ),
    ]
