# Generated by Django 5.1.6 on 2025-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_mbti_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.CharField(blank=True, choices=[('-', '-'), ('INTJ', 'INTJ:想像力が豊かで、戦略的な思考の持ち主。あらゆる物事に対して計画を立てる。'), ('INTP', 'INTP:貪欲な知識欲を持つ革新的な発明家'), ('ENTJ', 'ENTJ:大胆で想像力豊か、かつ強い意志を持つ指導者。常に道を見つけるか、道を切り開く。'), ('ENTP', 'ENTP:賢くて好奇心旺盛な思考家。知的挑戦には必ず受けて立つ。'), ('INFJ', 'INFJ:物静かで神秘的だが、人々を非常に勇気づける飽くなき理想主義者'), ('ENFJ', 'ENFJ:カリスマ性があり、人々を励ますリーダー。聞く人を魅了する。'), ('INFP', 'INFP:詩人肌で親切な利他主義者。良い物事のためなら、いつでも懸命に手を差し伸べる。'), ('ENFP', 'ENFP:情熱的で独創力があり、かつ社交的な自由人。常に笑いほほ笑みの種を見つけられる。'), ('ISTJ', 'ISTJ:実用的で事実に基づいた思考の持ち主。その信頼性は紛れもなく本物。'), ('ISFJ', 'ISFJ:非常に献身的で心の温かい擁護者。いつでも大切な人を守る準備ができている。'), ('ESTJ', 'ESTJ:優秀な管理者で、物事や人々を管理する能力にかけては、右に出る者はいない。'), ('ESFJ', 'ESFJ:非常に思いやりがあり社交的で、人気がある。常に熱心に人々に手を差し伸べている。'), ('ESTP', 'ESTP:賢くてエネルギッシュで、非常に鋭い知覚の持ち主。危険と隣り合わせの人生を心から楽しむ。'), ('ISTP', 'ISTP:大胆で実践的な思考を持つ実験者。あらゆる道具を使いこなす。'), ('ISFP', 'ISFP:柔軟性と魅力がある芸術家。常に進んで物事を探索し経験しようとする。'), ('ESFP', 'ESFP:自発性がありエネルギッシュで熱心なエンターテイナー。周りが退屈することは決してない。')], max_length=4, null=True, verbose_name='MBTI Type'),
        ),
    ]
