# Generated by Django 5.1.6 on 2025-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_created_pic_profile_updated_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_month_day',
            field=models.DateField(blank=True, default='2000-12-31', null=True, verbose_name='Birth Month/Day'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Birth'),
        ),
    ]
