# Generated by Django 5.1.6 on 2025-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_group_created_pic_group_updated_pic'),
        ('thread', '0001_initial'),
        ('user', '0022_profile_caretaker01_profile_caretaker02_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='thread_profiles', to='thread.thread'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_profiles', to='group.group'),
        ),
    ]
