# Generated by Django 5.1.6 on 2025-04-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_profile_threads_alter_profile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='FriendshipPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_returned', models.BooleanField(default=False)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_point_logs1', to='user.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_point_logs2', to='user.profile')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('profile1_id__lt', models.F('profile2_id'))), name='check_profile_order_in_log')],
                'unique_together': {('profile1', 'profile2', 'created_at')},
            },
        ),
    ]
