# Generated by Django 5.1.6 on 2025-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_profile_birth_month_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='profile_pk',
        ),
        migrations.AlterField(
            model_name='profile',
            name='memberid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Member Id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nick Name'),
        ),
    ]
