# Generated by Django 5.1.6 on 2025-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_profile_profile_pk_alter_profile_memberid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_cource',
            field=models.CharField(blank=True, choices=[('-', '-'), ('trial', 'トライアル会員(1ヶ月2日間のみ)'), ('bronze', 'ブロンズ会員(1ヶ月5日間のみ)'), ('gold', 'ゴールド会員(1ヶ月10日間のみ)'), ('platinum', 'プラチナ会員(1ヶ月何度でも利用可能)'), ('premium', 'プレミアム会員(ゴールド会員特典＋全コース受講可)')], max_length=100, null=True, verbose_name='Contract Cource'),
        ),
    ]
